"""empty message

Revision ID: fbb1bfced575
Revises: 8130f4b10c98
Create Date: 2019-11-16 16:48:13.228704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb1bfced575'
down_revision = '8130f4b10c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_actived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_actived')
    # ### end Alembic commands ###
